export { SingletnState, getSingletn, clearSingletns } from '@singletn/core'
export type { SingletnType  } from '@singletn/core'
export * from './as-signal'
export * from './context'
export * from './controller'
export * from './hooks/use-local-singletn'
export * from './hooks/use-singletn'
export * from './hooks/use-singletn-state'
